import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/Auth/AuthProvider";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "shop 3d",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
        <div>
          <header className="sticky top-0 z-50 backdrop-blur-md">
            <Navbar/>
          </header>
          <main className="max-w-10/12 mx-auto min-h-screen">
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </main>
          <footer>
            <Footer></Footer>
          </footer>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
